### ISSUE TITLE
Enabling the  Full Screen Fog Render Feature on the Universal Renderer Data Asset leads to an error and no fog being displayed

### ISSUE THREAD

**Issue by 0Flush0** [meryuhi/URPFog#1]
Hi,

i wanted to use the height based fog for a project i am working on, because unity just supports normal fog in URP. 
But when enabling the Full Screen Fog render feature on the asset, the following error occures and there is no visual output:

![grafik](https://github.com/meryuhi/URPFog/assets/93215916/f35fa392-b1ea-44ae-b3aa-1ab4b5eecac2)
**Error**
![grafik](https://github.com/meryuhi/URPFog/assets/93215916/acf5bd1e-1c4b-4bab-9fae-dc82018a7ea3)

Unity Version: 2022.3.12f
Thanks in advance!

**Comment by meryuhi** [comment]
Thank you for using it!
Have you set up volume in the scene?

**Comment by 0Flush0** [comment]
Thanks for you quick response,

the component is set up as global, i do have normal fog enabled, but turning it off does not seem to change the matter. 
Also the full screen render pass render feature does work. 
![grafik](https://github.com/meryuhi/URPFog/assets/93215916/d3430692-9949-48ab-b809-11da14429cf9)

**Comment by meryuhi** [comment]
OK, I didn't reproduce the issue on Unity 2022.3.13f, so sorry for needing more information.

- Is it possible to render in a new scene (only set up volume)?
- Clone this project and open SampleScene.unity to see if any errors still occur?
- Can you provide me with error log including stack information?

Or you can also send me your minimal example project, thanks.

**Comment by 0Flush0** [comment]
Fixed the issue by seperating the assets on different renderers.
 Thanks for this great asset!
