### ISSUE TITLE
FullscreenFog is generating memory garbage every frame (GC.Alloc)

### ISSUE THREAD

**Issue by juliodutra2003** [meryuhi/URPFog#3]
Hello,

Thanks for sharing this pacakge!
I'm trying to use it i na fullscreen mode.
Unity 2022.3.32f1
URP 14.0.11

As can be seing in the image bellow, 20B of memory garbage is generated every frame.

![image](https://github.com/user-attachments/assets/416c8251-30e3-4ef2-9006-6497d44e2bd2)

**Comment by meryuhi** [comment]
Hi, Thanks for your report! It has just been fixed. c0b6d9a81f7e9c1f58b6069ef38c8f6ec3636657

**Comment by juliodutra2003** [comment]
wow! that was fast! :)
thanks a lot!
