### ISSUE TITLE
Package does not work without Compatability Mode in Unity 6

### ISSUE THREAD

**Issue by Oskar-Norberg** [meryuhi/URPFog#4]
Package does not work without enabling compatibility mode which disable Render Graph.

Unity 6 ver 6000.0.23f1

**Comment by meryuhi** [comment]
Well, I added Render Graph support for urp 17. Also works in compatibility mode.

**Comment by Oskar-Norberg** [comment]
Thank you very much! Looking forward to using your effect in a project :D
